### PR TITLE
Updated FeatureDefinitions, tests and Description

### PR DESCRIPTION
**Pull request by itismeghasyam**
#### FEATURE DEFINITIONS:
- FeatureDefinitions.md updated to have new descriptions from the tremor paper

#### TESTS:
- test_utils updated for window_signal
- test_get_tapping_features, now includes test for depress_threshold parameter

#### DESCRIPTION:
Added the following line to Description 
`Encoding: UTF-8`
to get rid off the following warning
`roxygen2 requires Encoding: UTF-8`
- rxoygenized the package

### Addresses issues:
- #76 (look at issue for detailed comment)
- #83 
- #84  
- #85 (look at issue for detailed comment)

### CODE REVIEW

**Comment by philerooski** [comment]
The 10 failing tests on Travis are due to #103 . Only one test failed running `devtools::test()` in my local environment.

**Comment by itismeghasyam** [comment]
@th1vairam,
I agree with @philerooski on this. 
I also got one test failure on my computer when I run `devtools::test()`, and it is the one regarding the `tag_outlier_windows_`, i.e #85

**Comment by itismeghasyam** [comment]
@philerooski can you download and run `devtools::test()` on your local branch now?

I have updated the PR regarding #85

**Comment by itismeghasyam** [comment]
Major changes to test_utils  …
- Almost all tests now have a hardcoded(HC) example, the data for these is stored in R/sysdata.rda, unexposed to the user(i.e ::: instead of ::)
- The ones that do not have a HC, have been mentioned in issues

**Pull request merged**
