### PR TITLE
Documentation and time domain summary 

### PR DESCRIPTION
**Pull request by itismeghasyam**
- #107 with the fix we agreed on the issue thread - looping the dfa statement with a tryCatch
- #135 Not possible to define a metric like this
- #141 Documented `heartrate_data` and `tap_data` in R/data.R
- #142 All function parameters are now documented

### CODE REVIEW

**Comment by philerooski** [comment]
A few questions to help me understand the data (feel free to respond in-person):

* Is it possible to identify exactly (Synapse ID of table, recordId) where the heartrate and tap data came from?
* How are the axes arranged on the screen? In the past, iPhones had the origin in the top left corner. I don't know if they still do that or if we record the coordinates with the origin somewhere else.
* Can we reference the papers where these assays were introduced? Or are these assays being introduced in a future study?

**Comment by itismeghasyam** [comment]
- I don't think I remember exactly what recordID the heart rate and the tap data came from :/
- This once again not sure how the x and y indices are measured, need to ask Elias/Woody about that, but my guess is the origin is the left hand top corner
- The tap assay? We can reference our mPower paper

**Comment by philerooski** [comment]
> The tap assay? We can reference our mPower paper
Great. Otherwise our users are in the dark about what exactly a "tap assay" entails. Same with heart rate.

**Comment by itismeghasyam** [comment]
For the heart rate, we currently have no papers. I did try to give a little bit of detail on the dataset 
`?mhealthtools::heartrate_data`, but agreed that it would be better with a reference. 

We will update the reference once anything related to CRF gets published.

**Comment by philerooski** [comment]
Though what would be even better is if you could include a sentence or two describing what each assay is and how the data was obtained. The assays are simple enough we might as well tell the user what they are in the data description rather than sending them off to read a paper.

**Comment by itismeghasyam** [comment]
I like the idea, will update it on my next commit with vignettes

**Comment by philerooski** [comment]
@itismeghasyam Do you want to make a commit here to resolve #141 or are you going to do so in a separate PR?

**Comment by itismeghasyam** [comment]
#141 is addressed. I added a few lines of description about how the heartrate_data and tap_data were collected.

#160 is also addressed.
#157 A new vignette called 'Feature Definitions' is added
#153 This is because of the way `devtools::install_github()` works, since the default option for `build_vignettes = FALSE`.So to use `browseVignettes()`, we need to use `devtools::install_github('Sage-Bionetworks/mhealthtools', build_vignettes = TRUE)`. This is mentioned in the installation section of the README


Regarding #144  I removed the sensors and modules vignettes for now. Will update them in the next PR

**Pull request merged**
